import "dotenv/config";

export const ENV = {

PORT : process.env.PORT,
CORS_ORIGIN : process.env.CORS_ORIGIN,
MONGODB_URI : process.env.MONGODB_URI,
RESEND_API_SECRET : process.env.RESEND_API_SECRET,
EMAIL_FROM : process.env.EMAIL_FROM,
EMAIL_FROM_NAME : process.env.EMAIL_FROM_NAME,
CLOUDINARY_CLOUD_NAME : process.env.CLOUDINARY_API_SECRET,
CLOUDINARY_API_KEY : process.env.CLOUDINARY_API_SECRET,
CLOUDINARY_API_SECRET : process.env.CLOUDINARY_API_SECRET,
JWT_SECRET : process.env.JWT_SECRET,
CLIENT_URL : process.env.CLIENT_URL

}


